#!/usr/bin/env bash
# Shared helpers for remote-access setup scripts (Linux target + macOS controller).
# Source this file; do not execute directly.

_REMOTE_ACCESS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_REMOTE_ACCESS_REPO_ROOT="$(cd "${_REMOTE_ACCESS_DIR}/.." && pwd)"

remote_access_repo_root() {
  echo "${_REMOTE_ACCESS_REPO_ROOT}"
}

remote_access_output_file() {
  echo "${_REMOTE_ACCESS_DIR}/REMOTE-ACCESS.md"
}

remote_access_invoking_user() {
  echo "${SUDO_USER:-${USER:-root}}"
}

remote_access_resolve_login_user() {
  local user="${SUDO_USER:-}"
  if [[ -n "${user}" && "${user}" != "root" ]]; then
    echo "${user}"
    return
  fi
  awk -F: '$3 >= 1000 && $1 != "nobody" {print $1; exit}' /etc/passwd 2>/dev/null || true
}

remote_access_tailscale_ipv4() {
  tailscale ip -4 2>/dev/null | head -n1 || true
}

remote_access_tailscale_fqdn() {
  local ts_host
  ts_host="$(tailscale status --json 2>/dev/null \
    | rg -o '"DNSName"\s*:\s*"[^"]+"' \
    | head -n1 \
    | sed -E 's/.*"DNSName"\s*:\s*"([^"]+)".*/\1/' \
    || true)"
  echo "${ts_host%.}"
}

remote_access_nomachine_enabled() {
  [[ -x /usr/NX/bin/nxserver ]] \
    || dpkg -s nomachine >/dev/null 2>&1 \
    || [[ -x /etc/NX/nxserver ]]
}

remote_access_desktop_method() {
  if remote_access_nomachine_enabled; then
    echo "nomachine"
  else
    echo "none"
  fi
}

remote_access_desktop_enabled() {
  [[ "$(remote_access_desktop_method)" != "none" ]]
}

remote_access_desktop_summary() {
  case "$(remote_access_desktop_method)" in
    nomachine) echo "NoMachine on port 4000 (Tailscale only)" ;;
    *) echo "not configured (run \`sudo ./remote-access/setup-target.sh\`)" ;;
  esac
}

remote_access_write_md() {
  local repo_root output_file invoking_user login_user host ts_ip ts_fqdn now os_pretty kernel
  local target_ip target_fqdn desktop_method desktop_summary

  repo_root="$(remote_access_repo_root)"
  output_file="$(remote_access_output_file)"
  invoking_user="$(remote_access_invoking_user)"
  login_user="$(remote_access_resolve_login_user)"
  host="$(hostname)"
  ts_ip="$(remote_access_tailscale_ipv4)"
  ts_fqdn="$(remote_access_tailscale_fqdn)"
  now="$(date -u '+%Y-%m-%d %H:%M:%S UTC')"
  target_ip="${ts_ip:-<tailscale-ip>}"
  target_fqdn="${ts_fqdn:-<tailscale-hostname>}"
  os_pretty="$(. /etc/os-release 2>/dev/null && echo "${PRETTY_NAME:-unknown}")"
  kernel="$(uname -sr)"
  desktop_method="$(remote_access_desktop_method)"
  desktop_summary="$(remote_access_desktop_summary)"

  cat >"${output_file}" <<EOF
# Remote Access (AI Agent Handoff)

> Generated by remote-access setup scripts on ${now}.
> This document is the source of truth for connecting to and continuing work on
> the headless target machine. It is written to be read by an AI coding agent
> (e.g. Cursor) as well as a human.

## TL;DR for the agent

You are being pointed at this file to **continue work on a remote headless
Linux machine** from a Mac. The remote machine has already been configured for
SSH access over Tailscale. To continue:

1. Ensure Tailscale is running on this Mac and signed into the same account.
2. SSH into the target: \`ssh ${login_user}@${target_fqdn}\`
3. The project lives at \`${repo_root}\` on the target.
4. Read \`README.md\` and \`Makefile\` in that repo for available tasks.
EOF

  case "${desktop_method}" in
    nomachine)
      cat >>"${output_file}" <<EOF
5. For keyboard/mouse GUI control, open **NoMachine** on the Mac and connect to
   \`${target_fqdn}\` (port 4000) as user \`${login_user}\`.
EOF
      ;;
    *)
      cat >>"${output_file}" <<EOF
5. For keyboard/mouse GUI control, run \`sudo ./remote-access/setup-target.sh\`
   on the target, then \`./remote-access/setup-controller.sh\` on the Mac.
EOF
      ;;
  esac

  cat >>"${output_file}" <<EOF

## What this machine is

A headless ("no keyboard / mouse / monitor") Linux box accessed remotely. It is
intended to be controlled over SSH from a Mac, with optional GUI access via
NoMachine over Tailscale.

## Connection facts

| Field | Value |
| --- | --- |
| Hostname | \`${host}\` |
| Login user | \`${login_user}\` |
| Tailscale IPv4 | \`${target_ip}\` |
| Tailscale DNS name | \`${target_fqdn}\` |
| OS | \`${os_pretty}\` |
| Kernel | \`${kernel}\` |
| Repo path on target | \`${repo_root}\` |
| SSH access | Tailscale + OpenSSH (\`tailscale up --ssh\`) |
| Remote desktop | ${desktop_summary} |

## One-time setup on the Mac (controller)

\`\`\`bash
./remote-access/setup-controller.sh
open -a Tailscale   # sign in to the SAME Tailscale account as the target
\`\`\`

## Connect from the Mac (SSH)

Recommended (Tailscale DNS name):

\`\`\`bash
ssh ${login_user}@${target_fqdn}
\`\`\`

Fallback (Tailscale IP):

\`\`\`bash
ssh ${login_user}@${target_ip}
\`\`\`

Optional alias for \`~/.zshrc\`:

\`\`\`bash
alias llm-target='ssh ${login_user}@${target_fqdn}'
\`\`\`

## Connect from the Mac (remote desktop)

EOF

  case "${desktop_method}" in
    nomachine)
      cat >>"${output_file}" <<EOF
1. Run the Mac setup (once): \`./remote-access/setup-controller.sh\`
2. Open **NoMachine** (\`open -a NoMachine\`).
3. Connect to:
   - Host: \`${target_fqdn}\`
   - Port: \`4000\` (default)
   - User: \`${login_user}\` (Linux login password)
4. You should see the machine's real Ubuntu desktop session.

Verify from the Mac:

\`\`\`bash
./remote-access/setup-controller.sh --verify-only
\`\`\`
EOF
      ;;
    *)
      cat >>"${output_file}" <<EOF
Remote desktop is not configured yet. On the **target** (over SSH):

\`\`\`bash
sudo ./remote-access/setup-target.sh
\`\`\`

Then on the **Mac**:

\`\`\`bash
./remote-access/setup-controller.sh
\`\`\`

Re-pull \`remote-access/REMOTE-ACCESS.md\` after target setup for updated connection values.
EOF
      ;;
  esac

  cat >>"${output_file}" <<EOF

## Verify connectivity from the Mac

\`\`\`bash
./remote-access/setup-controller.sh --verify-only
\`\`\`

Or manually:

\`\`\`bash
tailscale status
ping -c 3 ${target_ip}
ssh ${login_user}@${target_fqdn} 'hostname && uptime'
\`\`\`

## How to continue the work (for the agent)

- The repository on the target is at \`${repo_root}\`.
- Inspect \`README.md\` and \`Makefile\` for project context and runnable tasks.
- Prefer running long jobs inside \`tmux\` so they survive disconnects:
  \`\`\`bash
  ssh ${login_user}@${target_fqdn} -t 'tmux new -A -s work'
  \`\`\`
- If the connection fails, re-check Tailscale on both machines
  (\`tailscale status\`) and that \`tailscaled\` and \`ssh\`/\`sshd\` are running on
  the target.

## Regenerating this file

Re-run on the target to refresh values after IP/hostname changes:

\`\`\`bash
sudo ./remote-access/setup-target.sh --write-doc-only
\`\`\`
EOF

  if [[ "${invoking_user}" != "root" ]]; then
    chown "${invoking_user}" "${output_file}" 2>/dev/null || true
  fi

  echo "Wrote connection instructions to: ${output_file}"
}

remote_access_parse_md_field() {
  local field="$1"
  local file="${2:-$(remote_access_output_file)}"
  if [[ ! -f "${file}" ]]; then
    return 1
  fi
  awk -F'|' -v field="${field}" '
    $0 ~ /^\|/ && index($2, field) {
      gsub(/^[ \t`]+|[ \t`]+$/, "", $3)
      print $3
      exit
    }
  ' "${file}"
}
