#!/usr/bin/env bash
set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo "Run this script as root (use sudo)." >&2
  exit 1
fi

# Resolve the repo root from this script's location so the output file
# lands in a predictable, committable place regardless of cwd.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUTPUT_FILE="${REPO_ROOT}/REMOTE-ACCESS.md"

# When run under sudo, commit-related ownership should belong to the
# invoking user, not root.
INVOKING_USER="${SUDO_USER:-root}"

need_cmd() {
  command -v "$1" >/dev/null 2>&1
}

install_pkgs() {
  if need_cmd apt-get; then
    apt-get update
    apt-get install -y curl openssh-server
  elif need_cmd dnf; then
    dnf install -y curl openssh-server
  elif need_cmd pacman; then
    pacman -Sy --noconfirm curl openssh
  elif need_cmd zypper; then
    zypper --non-interactive install curl openssh
  else
    echo "Unsupported package manager. Install curl + OpenSSH server manually." >&2
    exit 1
  fi
}

install_tailscale() {
  if need_cmd tailscale && need_cmd tailscaled; then
    echo "Tailscale already installed."
    return
  fi

  # Official installer supports major Linux distros.
  curl -fsSL https://tailscale.com/install.sh | sh
}

enable_ssh_service() {
  local service_name=""
  if systemctl list-unit-files | rg -q '^ssh\.service'; then
    service_name="ssh"
  elif systemctl list-unit-files | rg -q '^sshd\.service'; then
    service_name="sshd"
  else
    echo "Could not find SSH service unit (ssh/sshd)." >&2
    exit 1
  fi

  systemctl enable --now "${service_name}"
}

enable_tailscale_service() {
  systemctl enable --now tailscaled
}

bring_up_tailscale() {
  # --ssh enables Tailscale SSH to avoid opening LAN ports.
  # This may print a login URL on first run.
  tailscale up --ssh
}

show_status() {
  echo
  echo "===== STATUS ====="
  systemctl --no-pager --full status tailscaled | sed -n '1,8p'
  systemctl --no-pager --full status ssh 2>/dev/null | sed -n '1,8p' || true
  systemctl --no-pager --full status sshd 2>/dev/null | sed -n '1,8p' || true
  echo
  tailscale status || true
  echo
  echo "Hostname: $(hostname)"
  echo "User accounts on this box (choose one for ssh login):"
  awk -F: '$3 >= 1000 && $1 != "nobody" {print " - " $1}' /etc/passwd || true
}

# Pick the best login user for ssh: prefer the human who ran sudo,
# otherwise fall back to the first regular account.
resolve_login_user() {
  if [[ -n "${SUDO_USER:-}" && "${SUDO_USER}" != "root" ]]; then
    echo "${SUDO_USER}"
    return
  fi
  awk -F: '$3 >= 1000 && $1 != "nobody" {print $1; exit}' /etc/passwd
}

generate_instructions_file() {
  local host login_user ts_ip ts_host ts_fqdn now
  host="$(hostname)"
  login_user="$(resolve_login_user)"
  ts_ip="$(tailscale ip -4 2>/dev/null | head -n1 || true)"
  # MagicDNS short name and FQDN (if available).
  ts_host="$(tailscale status --json 2>/dev/null | rg -o '"DNSName"\s*:\s*"[^"]+"' | head -n1 | sed -E 's/.*"DNSName"\s*:\s*"([^"]+)".*/\1/' || true)"
  ts_fqdn="${ts_host%.}"
  now="$(date -u '+%Y-%m-%d %H:%M:%S UTC')"

  local target_ip="${ts_ip:-<tailscale-ip>}"
  local target_fqdn="${ts_fqdn:-<tailscale-hostname>}"

  cat >"${OUTPUT_FILE}" <<EOF
# Remote Access

Generated by \`scripts/setup-target-headless-remote.sh\` on ${now}.

This headless machine is reachable over Tailscale via SSH. Run the commands
below **from your Mac Studio**.

## Target machine

| Field | Value |
| --- | --- |
| Hostname | \`${host}\` |
| Login user | \`${login_user}\` |
| Tailscale IPv4 | \`${target_ip}\` |
| Tailscale DNS name | \`${target_fqdn}\` |

## One-time setup on your Mac

\`\`\`bash
./scripts/setup-mac-controller.sh
open -a Tailscale   # sign in to the SAME Tailscale account
\`\`\`

## Connect from your Mac

Using the Tailscale DNS name (recommended):

\`\`\`bash
ssh ${login_user}@${target_fqdn}
\`\`\`

Or using the Tailscale IP:

\`\`\`bash
ssh ${login_user}@${target_ip}
\`\`\`

## Optional: shell alias

Add to your \`~/.zshrc\` on the Mac:

\`\`\`bash
alias llm-target='ssh ${login_user}@${target_fqdn}'
\`\`\`

## Verify from the Mac

\`\`\`bash
tailscale status
ping -c 3 ${target_ip}
\`\`\`
EOF

  # Make the file committable by the human user, not root.
  if [[ "${INVOKING_USER}" != "root" ]]; then
    chown "${INVOKING_USER}" "${OUTPUT_FILE}" 2>/dev/null || true
  fi

  echo "Wrote connection instructions to: ${OUTPUT_FILE}"
}

main() {
  echo "Installing prerequisites..."
  install_pkgs
  echo "Installing Tailscale..."
  install_tailscale
  echo "Enabling SSH..."
  enable_ssh_service
  echo "Enabling Tailscale daemon..."
  enable_tailscale_service
  echo "Bringing Tailscale online..."
  bring_up_tailscale
  show_status
  echo "Writing connection instructions..."
  generate_instructions_file

  cat <<EOF

Next steps:
1) Commit the generated instructions to git:
     git add REMOTE-ACCESS.md && git commit -m "Add remote access instructions"
     git push
2) On your Mac, pull the repo and open REMOTE-ACCESS.md.
3) Copy/paste the ssh command from that file.
EOF
}

main "$@"
